### ISSUE TITLE
wxParse作者信息更新

### ISSUE THREAD

**Issue by icindy** [yuwanli/octopus-wxapp#1]
我是wxParse作者 

我并非供职白鹭，感谢支持
我目前供职便利蜂 感谢使用wxParse 
同时希望多多交流 和 同时PR

**Comment by yuwanli** [comment]
哈哈，不好意思，当时参加的是白鹭时代举办的小程序的分享，记错了。
以后多多交流，前端菜鸟还得多多跟你学习！
